# Память для Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# IntelliJ IDEA пока не полностью совместима с configuration cache
org.gradle.configuration-cache=false

# Версии Fabric (сверено с fabricmc.net/develop и рабочими модами под 1.21.11)
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.141.6+1.21.11
cloth_config_version=21.11.153
modmenu_version=17.0.0

# Параметры мода
mod_version=1.3.0
maven_group=com.parkourmod
archives_base_name=parkourmod
